[package]
name = "adventofcode"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
day1 = { path = "../day1" }
day2 = { path = "../day2" }
day3 = { path = "../day3" }
day4 = { path = "../day4" }